spring.jpa:
  database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect
  hibernate.ddl-auto: update
  show-sql: true
  # https://stackoverflow.com/a/26882135:
  generate-ddl: true
pepperpal:
  db:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:soilData.db
  api:
    openapi:
      dev-url: http://localhost:8080
      prod-url: http://localhost:8080
