spring:
  jackson.deserialization.fail-on-null-for-primitives: false
  datasource:
    url: jdbc:sqlite:soilData.db
    driver-class-name: org.sqlite.JDBC
  sql.init.mode: always
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    # https://stackoverflow.com/a/26882135:
    generate-ddl: true

pepperpal.api:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080
