<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>de.jaypi4c.pepperpal</groupId>
        <artifactId>pepperpal-parent</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>bot</artifactId>
    <packaging>jar</packaging>

    <name>Bot</name>
    <description>Mastodon Bot for chili rest api</description>

    <properties>
        <bigbone.version>2.0.0</bigbone.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.pattafeufeu</groupId>
            <artifactId>bigbone</artifactId>
            <version>${bigbone.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-restclient</artifactId>
        </dependency>
    </dependencies>

</project>
